# Generated by Django 5.1.6 on 2025-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
