# Generated by Django 5.1.6 on 2025-03-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='featured',
        ),
    ]
