# Generated by Django 5.1.6 on 2025-03-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='title',
        ),
    ]
