# Generated by Django 5.1.6 on 2025-04-07 12:36

import products.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='media',
            field=models.FileField(blank=True, null=True, storage=products.storages.ProtectedStorage, upload_to='products/'),
        ),
    ]
